# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-zddition-github-io'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}
- {name: 'Colored Circle Club', url: 'ccc.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://zddition.github.io/'}
- {icon: 'twitter',    link: 'https://zddition.github.io/'}
- {icon: 'linkedin',   link: 'https://zddition.github.io/'}
- {icon: 'envelope',   link: 'https://zddition.github.io/'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
